=== joelhoffmann/DHBW_SEM2_SE_XML/lichttechnik-schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lichttechnik" type="lichttechnikType">
    </xs:element>
    <!--root with child-->
    <xs:complexType name="lichttechnikType">
        <xs:sequence>
            <xs:element name="leds" minOccurs="0">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element type="movinglightsType" name="movinglights" minOccurs="0"/>
                        <xs:element type="barsType" name="bars" minOccurs="0"/>
                        <xs:element type="spotsType" name="spots" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="lasers" minOccurs="0">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element type="projectorType" name="projector" minOccurs="0">
                        </xs:element>
                        <xs:element type="showlaserType" name="showlaser" minOccurs="0">
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="halogene" minOccurs="0">
                <xs:complexType >
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element type="konventionelType" name="konventionel" minOccurs="0">
                        </xs:element>
                        <xs:element type="followspotType" name="followspot" minOccurs="0">
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!--grandchilds-->
    <xs:complexType name="movinglightsType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="bewegungType" name="bewegung"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="xs:integer" name="effekte"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="xs:integer" name="kanäle"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="barsType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="bewegungType" name="bewegung"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="xs:byte" name="kanäle"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="spotsType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="xs:string" name="effekte"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="xs:byte" name="kanäle"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectorType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
            <xs:element type="xs:string" name="auflösung"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="showlaserType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="bewegungType" name="bewegung"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="xs:string" name="effekte"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="xs:byte" name="kanäle"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="konventionelType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="xs:byte" name="kanäle"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="followspotType">
        <xs:sequence>
            <xs:element type="xs:string" name="hersteller"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="lichtleistungType" name="lichtleistung"/>
            <xs:element type="bewegungType" name="bewegung" minOccurs="0"/>
            <xs:element type="abstrahlwinkelType" name="abstrahlwinkel"/>
            <xs:element type="lebenserwartungType" name="lebenserwartung" minOccurs="0"/>
            <xs:element type="leistungsaufnahmeType" name="leistungsaufnahme"/>
            <xs:element type="gewichtType" name="gewicht"/>
            <xs:element type="lichtquelleType" name="lichtquelle"/>
        </xs:sequence>
    </xs:complexType>
    <!--grandgrandchilds-->
    <xs:complexType name="bewegungType">
        <xs:sequence>
            <xs:element type="xs:decimal" name="tilt" minOccurs="0"/>
            <xs:element type="xs:decimal" name="pan" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="abstrahlwinkelType">
        <xs:sequence>
            <xs:element type="VonBisType" name="von">
            </xs:element>
            <xs:element type="VonBisType" name="bis" minOccurs="0">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="lichtquelleType">
        <xs:sequence>
            <xs:element type="xs:byte" name="menge"/>
            <xs:element type="xs:string" name="produkt"/>
        </xs:sequence>
    </xs:complexType>
    <!--attribiutes-->
    <xs:complexType name="lebenserwartungType">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute type="zeitType" name="einheit" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="leistungsaufnahmeType">
        <xs:simpleContent>
            <xs:extension base="xs:short">
                <xs:attribute type="xs:string" name="einheit" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="gewichtType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute type="xs:string" name="einheit" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="lichtleistungType">
        <xs:simpleContent>
            <xs:extension base="xs:double">
                <xs:attribute type="lichtmessungType" name="einheit" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!--extending types-->
    <xs:simpleType name="VonBisType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="720"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="lichtmessungType">
        <xs:restriction base="xs:string">
            <xs:pattern value="lumen"/>
            <xs:pattern value="ansi lumen"/>
            <xs:pattern value="lm"/>
            <xs:pattern value="candela"/>
            <xs:pattern value="cd"/>
            <xs:pattern value="Lux"/>
            <xs:pattern value="lx"/>
            <xs:pattern value="mW @ 450nm"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="zeitType">
        <xs:restriction base="xs:string">
            <xs:pattern value="h"/>
            <xs:pattern value="hours"/>
            <xs:pattern value="stunden"/>
            <xs:pattern value="years"/>
            <xs:pattern value="y"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== joelhoffmann/DHBW_SEM2_SE_XML/lichttechnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lichttechnik.xsl" type="text/xsl"?>
<!--<DOCTYPE lichttechnik SYSTEM "./lichttechnik.dtd">-->
<lichttechnik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./lichttechnik-schema.xsd">
    <!--Alle LED betreibene Lampen-->
    <leds>
        <!--Movinglights-->
        <movinglights>
            <hersteller>ROBE</hersteller>
            <name>Pointe</name>
            <lichtleistung einheit="lumen">9870</lichtleistung>
            <bewegung>
                <tilt>270</tilt>
                <pan>540</pan>
            </bewegung>
            <abstrahlwinkel>
                <von>2.5</von>
                <bis>20</bis>
            </abstrahlwinkel>
            <effekte>19</effekte>
            <lebenserwartung einheit="h">2500</lebenserwartung>
            <leistungsaufnahme einheit="W">470</leistungsaufnahme>
            <kanäle>30</kanäle>
            <gewicht einheit="kg">15</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Osram Sirius HRI 280 W RO (Leuchtmittel)</produkt>
            </lichtquelle>
        </movinglights>
        <!--LED Bar-->
        <bars>
            <hersteller>GLP</hersteller>
            <name>Impression X4</name>
            <lichtleistung einheit="lumen">1.920</lichtleistung>
            <bewegung> 
                <tilt>210</tilt>
            </bewegung>
            <abstrahlwinkel>
                <von>7</von>
                <bis>50</bis>
            </abstrahlwinkel>
            <lebenserwartung einheit="h">50000</lebenserwartung>
            <leistungsaufnahme einheit="W">400</leistungsaufnahme>
            <kanäle>20</kanäle>
            <gewicht einheit="kg">16</gewicht>
            <lichtquelle>
                <menge>20</menge>
                <produkt>LED</produkt>
            </lichtquelle>
        </bars>
        <!--LED Spots-->
        <spots>
            <hersteller>Expolite</hersteller>
            <name>Tour LED 50</name>
            <lichtleistung einheit="lumen">1.500</lichtleistung>
            <abstrahlwinkel>
                <von>16</von>
            </abstrahlwinkel>
            <effekte>ja</effekte>
            <lebenserwartung einheit="h">50000</lebenserwartung>
            <leistungsaufnahme einheit="W">70</leistungsaufnahme>
            <kanäle>15</kanäle>
            <gewicht einheit="kg">4,8</gewicht>
            <lichtquelle>
                <menge>14</menge>
                <produkt>LED</produkt>
            </lichtquelle>
        </spots>
    </leds>
    <!--Alle Laser-betreibene Geräte-->
    <lasers>
        <!--Projektoren-->
        <projector>
            <hersteller>BenQ</hersteller>
            <name>LK990</name>
            <lichtleistung einheit="ansi lumen">6000</lichtleistung>
            <lebenserwartung einheit="h">20000</lebenserwartung>
            <leistungsaufnahme einheit="W">655</leistungsaufnahme>
            <gewicht einheit="kg">20,2</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Laser</produkt>
            </lichtquelle>
            <auflösung>4k</auflösung>
        </projector>
        <!--Showlaser-->
        <showlaser>
            <hersteller>Carres Effects</hersteller>
            <name>IVL</name>
            <lichtleistung einheit="mW @ 450nm">5600</lichtleistung>
            <bewegung>
                <tilt>35</tilt>
            </bewegung>
            <abstrahlwinkel>
                <von>1</von>
                <bis>80</bis>
            </abstrahlwinkel>
            <effekte>ja</effekte>
            <lebenserwartung einheit="">nicht angegeben</lebenserwartung>
            <leistungsaufnahme einheit="W">125</leistungsaufnahme>
            <kanäle>25</kanäle>
            <gewicht einheit="kg">16</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Laser</produkt>
            </lichtquelle>
        </showlaser>
    </lasers>
    <!--Alle Halogene-->
    <halogene>
        <!--konventionel-->
        <konventionel>
            <hersteller>Tibo</hersteller>
            <name>Frosnel 525</name>
            <lichtleistung einheit="lumen">23300</lichtleistung>
            <abstrahlwinkel>
                <von>85</von>
                <bis>85</bis>
            </abstrahlwinkel>
            <lebenserwartung einheit="h">8000</lebenserwartung>
            <leistungsaufnahme einheit="W">250</leistungsaufnahme>
            <kanäle>2</kanäle>
            <gewicht einheit="kg">7,4</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Discharge</produkt>
            </lichtquelle>
        </konventionel>
        <!--Follow Spot-->
        <followspot>
            <hersteller>ROBERT JULIAT</hersteller>
            <name>Aramis</name>
            <lichtleistung einheit="lumen">240000</lichtleistung>
            <abstrahlwinkel>
                <von>4.5</von>
                <bis>8</bis>
            </abstrahlwinkel>
            <lebenserwartung einheit="h">500</lebenserwartung>
            <leistungsaufnahme einheit="W">2500</leistungsaufnahme>
            <gewicht einheit="kg">59</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>HMI 2500 W/S XS</produkt>
            </lichtquelle>
        </followspot>
    </halogene>
</lichttechnik>

=== joelhoffmann/DHBW_SEM2_SE_XML/lichttechnik-mistakes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<DOCTYPE lichttechnik SYSTEM "./lichttechnik.dtd">-->
<lichttechnik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./lichttechnik-schema.xsd">
    <!--Alle LED betreibene Lampen-->
    <leds>
        <!--Movinglights-->
        <movinglights>
            <hersteller>ROBE</hersteller>
            <name>Pointe</name>
            <lichtleistung einheit="lumen">9870</lichtleistung>
            <bewegung>
                <tilt>270</tilt>
                <pan>540</pan>
            </bewegung>
            <abstrahlwinkel>
                <von>2.5</von>
                <bis>20</bis>
            </abstrahlwinkel>
            <effekte>19</effekte>
            <lebenserwartung einheit="h">2500</lebenserwartung>
            <leistungsaufnahme einheit="W">470</leistungsaufnahme>
            <kan채le>30</kan채le>
            <gewicht einheit="kg">15</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Osram Sirius HRI 280 W RO (Leuchtmittel)</produkt>
            </lichtquelle>
        </movinglights>
        <movinglights>
            <hersteller>ROBE</hersteller>
            <name>Pointe</name>
            <lichtleistung einheit="kg">9870</lichtleistung>
            <bewegung>
                <tilt>270</tilt>
                <pan>540</pan>
            </bewegung>
            <abstrahlwinkel>
                <von>-2.5</von>
                <bis>20</bis>
            </abstrahlwinkel>
            <effekte>19</effekte>
            <lebenserwartung einheit="h">2500</lebenserwartung>
            <leistungsaufnahme einheit="W">470</leistungsaufnahme>
            <kan채le>30</kan채le>
            <gewicht einheit="kg">15</gewicht>
            <lichtquelle>
                <menge>1</menge>
                <produkt>Osram Sirius HRI 280 W RO (Leuchtmittel)</produkt>
            </lichtquelle>
        </movinglights>
    </leds>
</lichttechnik>
